spring:
  application:
    name: secom
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SECOM
    password: SECOM
    driver-class-name: oracle.jdbc.driver.OracleDriver

server:
  port: 80

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: NULL
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kh.secom.member.model.vo

logging:
  level:
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.resultset: DEBUG
    jdbc.audit: DEBUG	

jwt:
  secret: ixT+57RqcN/H4zaeGMfDaiw32qxGOfO3MjY+XITjgNI=