spring:
  application:
    name: secom
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SECOM
    password: SECOM
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 80

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: VARCHAR
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kh.secom.member.model.vo, com.kh.secom.token.model.dto, com.kh.secom.board.model.dto, com.kh.secom.commnet.model.dto

logging:
  level:
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.resultset: DEBUG
    jdbc.audit: DEBUG	

jwt:
  secret: ixT+57RqcN/H4zaeGMfDaiw32qxGOfO3MjY+XITjgNI=

